### ISSUE TITLE
wave install --proxy install a Snapshot version, not a release version

### ISSUE THREAD

**Issue by nathmclean** [wavefrontHQ/wavefront-cli#12]
I'm using the CLI to install proxies on linux (Ubuntu 16) instances (on AWS) and it installs a SNAPSHOT version of the proxy, not a release as I would expect.

CLI version:
```
$ wave --version
0.0.114
```

Install command:
`wave install --proxy --wavefront-url=https://account.wavefront.com --api-token=token`

This results in version `4.33-SNAPSHOT` of the proxy being installed on the server (as reported by the Wavefront Dashboard).

I tested using the code generated under the 'Add Proxy' section of the Wavefront dashboard and this installed a release version -4.32 (I tested this on OSX)

```curl -sL \
    https://raw.githubusercontent.com/wavefrontHQ/homebrew-wavefront/master/sh/install.sh | \
    bash -s -- -p \
    -t 6b039c62-1a79-445c-adad-c0f8a65830cd \
    -u https://spaceape.wavefront.com/api/
```

Is there a way of forcing the installation of the latest release, rather than Snapshot?

**Comment by vikramraman** [comment]
Thanks for the feedback. We are aware of this issue and will be fixing it soon.

**Comment by vikramraman** [comment]
Has been fixed.
